# SITE SETTINGS
title: Vocabulary Maintenance Standard
url: "https://vms.tdwg.org"

# SOCIAL PROFILES
social:
  github: tdwg/vocab

# THEME SETTINGS
theme: minima
remote_theme: tdwg/petridish@main
github_edit: false
logo: /assets/theme/images/tdwg-logo-short.svg

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: ""
    values:
      layout: default
      toc: true
